// Districts (neighbourhoods) per city for the revenue estimator's searchable
// district field. These are the well-known districts of each city — a
// reasonable standard set. The client can edit or extend this list freely;
// it's the single source of truth for the field.
//
// `value` is a stable slug (used in form state / the API request body).
// `en` / `ar` are the display labels, picked by the active locale.

export type District = { value: string; en: string; ar: string };

export const DISTRICTS: Record<string, District[]> = {
  riyadh: [
    { value: "olaya", en: "Olaya", ar: "العليا" },
    { value: "al-malqa", en: "Al Malqa", ar: "الملقا" },
    { value: "al-yasmin", en: "Al Yasmin", ar: "الياسمين" },
    { value: "al-nakheel", en: "Al Nakheel", ar: "النخيل" },
    { value: "al-sahafa", en: "Al Sahafa", ar: "الصحافة" },
    { value: "al-aqiq", en: "Al Aqiq", ar: "العقيق" },
    { value: "hittin", en: "Hittin", ar: "حطين" },
    { value: "al-wurud", en: "Al Wurud", ar: "الورود" },
    { value: "al-muruj", en: "Al Muruj", ar: "المروج" },
    { value: "al-rabi", en: "Al Rabi", ar: "الربيع" },
    { value: "al-izdihar", en: "Al Izdihar", ar: "الازدهار" },
    { value: "al-ghadir", en: "Al Ghadir", ar: "الغدير" },
    { value: "al-rahmaniyah", en: "Al Rahmaniyah", ar: "الرحمانية" },
    { value: "qurtubah", en: "Qurtubah", ar: "قرطبة" },
    { value: "al-naseem", en: "Al Naseem", ar: "النسيم" },
    { value: "al-rawdah", en: "Al Rawdah", ar: "الروضة" },
    { value: "al-malaz", en: "Al Malaz", ar: "الملز" },
    { value: "al-wizarat", en: "Al Wizarat", ar: "الوزارات" },
    { value: "diplomatic-quarter", en: "Diplomatic Quarter", ar: "الحي الدبلوماسي" },
    { value: "granada", en: "Granada", ar: "غرناطة" },
    { value: "al-narjis", en: "Al Narjis", ar: "النرجس" },
    { value: "al-arid", en: "Al Arid", ar: "العارض" },
    { value: "al-qirawan", en: "Al Qirawan", ar: "القيروان" },
    { value: "al-murabba", en: "Al Murabba", ar: "المربع" },
  ],
  jeddah: [
    { value: "al-hamra", en: "Al Hamra", ar: "الحمراء" },
    { value: "al-shati", en: "Al Shati", ar: "الشاطئ" },
    { value: "al-rawdah", en: "Al Rawdah", ar: "الروضة" },
    { value: "al-salama", en: "Al Salama", ar: "السلامة" },
    { value: "al-naeem", en: "Al Naeem", ar: "النعيم" },
    { value: "al-zahra", en: "Al Zahra", ar: "الزهراء" },
    { value: "al-bawadi", en: "Al Bawadi", ar: "البوادي" },
    { value: "al-faisaliyah", en: "Al Faisaliyah", ar: "الفيصلية" },
    { value: "al-andalus", en: "Al Andalus", ar: "الأندلس" },
    { value: "al-safa", en: "Al Safa", ar: "الصفا" },
    { value: "al-marwah", en: "Al Marwah", ar: "المروة" },
    { value: "al-nahda", en: "Al Nahda", ar: "النهضة" },
    { value: "obhur-al-shamaliyah", en: "Obhur Al Shamaliyah", ar: "أبحر الشمالية" },
    { value: "obhur-al-janubiyah", en: "Obhur Al Janubiyah", ar: "أبحر الجنوبية" },
    { value: "al-khalidiyah", en: "Al Khalidiyah", ar: "الخالدية" },
    { value: "al-aziziyah", en: "Al Aziziyah", ar: "العزيزية" },
    { value: "al-mohammadiyah", en: "Al Mohammadiyah", ar: "المحمدية" },
    { value: "al-basateen", en: "Al Basateen", ar: "البساتين" },
    { value: "al-sharafiyah", en: "Al Sharafiyah", ar: "الشرفية" },
    { value: "al-balad", en: "Al Balad", ar: "البلد" },
    { value: "al-hamdaniyah", en: "Al Hamdaniyah", ar: "الحمدانية" },
    { value: "al-murjan", en: "Al Murjan", ar: "المرجان" },
  ],
  dammam: [
    { value: "al-shati", en: "Al Shati", ar: "الشاطئ" },
    { value: "al-faisaliyah", en: "Al Faisaliyah", ar: "الفيصلية" },
    { value: "al-mazruiyah", en: "Al Mazruiyah", ar: "المزروعية" },
    { value: "uhud", en: "Uhud", ar: "أحد" },
    { value: "al-adamah", en: "Al Adamah", ar: "العدامة" },
    { value: "al-jalawiyah", en: "Al Jalawiyah", ar: "الجلوية" },
    { value: "al-badiyah", en: "Al Badiyah", ar: "البادية" },
    { value: "al-noor", en: "Al Noor", ar: "النور" },
    { value: "al-rakah", en: "Al Rakah", ar: "الراكة" },
    { value: "ar-rabi", en: "Ar Rabi", ar: "الربيع" },
    { value: "king-fahd-suburb", en: "King Fahd Suburb", ar: "ضاحية الملك فهد" },
    { value: "al-anoud", en: "Al Anoud", ar: "العنود" },
    { value: "al-manar", en: "Al Manar", ar: "المنار" },
    { value: "al-amal", en: "Al Amal", ar: "الأمل" },
    { value: "al-firdaws", en: "Al Firdaws", ar: "الفردوس" },
    { value: "al-hamra", en: "Al Hamra", ar: "الحمراء" },
    { value: "al-muntazah", en: "Al Muntazah", ar: "المنتزه" },
    { value: "al-khaleej", en: "Al Khaleej", ar: "الخليج" },
    { value: "al-suq", en: "Al Suq", ar: "السوق" },
    { value: "al-athir", en: "Al Athir", ar: "الأثير" },
  ],
  khobar: [
    { value: "al-khobar-al-shamaliyah", en: "Al Khobar Al Shamaliyah", ar: "الخبر الشمالية" },
    { value: "al-khobar-al-janubiyah", en: "Al Khobar Al Janubiyah", ar: "الخبر الجنوبية" },
    { value: "al-aqrabiyah", en: "Al Aqrabiyah", ar: "العقربية" },
    { value: "al-hizam-al-akhdar", en: "Al Hizam Al Akhdar", ar: "الحزام الأخضر" },
    { value: "al-yarmuk", en: "Al Yarmuk", ar: "اليرموك" },
    { value: "al-rakah", en: "Al Rakah", ar: "الراكة" },
    { value: "al-bandariyah", en: "Al Bandariyah", ar: "البندرية" },
    { value: "al-ulaya", en: "Al Ulaya", ar: "العليا" },
    { value: "al-thuqbah", en: "Al Thuqbah", ar: "الثقبة" },
    { value: "al-hada", en: "Al Hada", ar: "الهدا" },
    { value: "ishbiliyah", en: "Ishbiliyah", ar: "إشبيلية" },
    { value: "al-kawthar", en: "Al Kawthar", ar: "الكوثر" },
    { value: "al-jisr", en: "Al Jisr", ar: "الجسر" },
    { value: "al-khuzama", en: "Al Khuzama", ar: "الخزامى" },
    { value: "al-bustan", en: "Al Bustan", ar: "البستان" },
    { value: "qurtubah", en: "Qurtubah", ar: "قرطبة" },
    { value: "al-sawari", en: "Al Sawari", ar: "الصواري" },
    { value: "al-andalus", en: "Al Andalus", ar: "الأندلس" },
    { value: "al-aziziyah", en: "Al Aziziyah", ar: "العزيزية" },
    { value: "al-hamra", en: "Al Hamra", ar: "الحمراء" },
  ],
};
